package aoc2022;

public enum Day {
	ONE, TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,TEN,
	ELEVEN,TWELVE,THIRTEEN,FOURTEEN,FIFTEEN,SIXTEEN,SEVENTEEN,EIGHTEEN,NINETEEN,
	TWENTY,TWENTYONE,TWENTYTWO,TWENTYTHREE,TWENTYFOUR,
}
